version: "3.7"
services:
  kong:
    image: kong/kong-gateway:${KONG_VERSION:-latest}
    container_name: kong
    restart: always
    network_mode: host
    environment:
      - TZ=${TZ:-Asia/Kolkata}
      - KONG_DATABASE=off
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
      - KONG_PORTAL=on
      - KONG_VITALS=on
      - KONG_PORTAL_GUI_URL=http://localhost:8003
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN:-127.0.0.1:8001}
      - KONG_PROXY_LISTEN=${KONG_PROXY_LISTEN:-0.0.0.0:8000, 0.0.0.0:8443 ssl http2}
      - KONG_NGINX_HTTP_RESOLVER=${KONG_NGINX_HTTP_RESOLVER:-8.8.8.8}
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_LOG_LEVEL=info
      - KONG_WORKER_STATE_UPDATE_FREQUENCY=1
      - KONG_LUA_PACKAGE_PATH=./opt/conf/?.lua;
      - KONG_PLUGINS=bundled
